import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import {
  TipCalculatorCtx,
  TipCalculatorProvider,
} from "@/context/calculatorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mini Testing Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-height-100vh bg-gray-200 max-w-[100vw] overflow-hidden">
          <Header />
          <main className="flex-1 flex justify-center items-center">
            <TipCalculatorProvider>{children}</TipCalculatorProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
